cloud:
  aws:
    region:
      static: us-west-1
      auto: false
    stack:
      auto: false
    end-point:
      uri: https://sqs.us-west-1.amazonaws.com/796731763832/MySQSQueue
    topic-arn: arn:aws:sns:us-west-1:796731763832:SNSTopic

server:
  port: 8081
